# Generated by Django 4.1 on 2024-04-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0002_alter_diary_options_alter_diary_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ('-datecreated',), 'verbose_name_plural': 'Diaries'},
        ),
        migrations.AddField(
            model_name='diary',
            name='dateupdated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
